variables:
  - &build_image woodpeckerci/plugin-docker-buildx:5.0
  - &build_settings
    repo: handspiker2/ci-tools
    dockerfile: ansible.Dockerfile
    tags:
      - ansible
    dry_run: true
    platforms: [linux/amd64]
  - &step_events [push, manual]

depends_on: 
  - base

steps:
- name: Build Ansible Image
  image: *build_image
  settings:
    <<: *build_settings
  when:
    branch:
      exclude:
      - ${CI_REPO_DEFAULT_BRANCH}
    event: *step_events

- name: Build&Publish Ansible Image
  image: *build_image
  settings:
    <<: *build_settings
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dry_run: false
  when:
    branch:
    - ${CI_REPO_DEFAULT_BRANCH}
    event: *step_events