variables:
  - &build_image woodpeckerci/plugin-docker-buildx:5.0
  - &built_image_tag base-${CI_COMMIT_SHA:0:8}-${CI_PIPELINE_NUMBER}
  - &step_events [push, manual]
  - &build_platforms [linux/amd64, linux/arm64]


steps:
- name: Build Base Image
  image: *build_image
  settings:
    repo: registry.ci.spikedhand.com/handspiker2/ci-tools
    dockerfile: base.Dockerfile
    tags: 
      - *built_image_tag
    dry_run: false
    platforms: *build_platforms
  when:
    event: *step_events

- name: Publish Image
  image: handspiker2/ci-tools:docker
  environment:
    DOCKER_USER:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
    IMAGE_TAG: *built_image_tag
  commands:
    - echo $$DOCKER_PASSWORD | skopeo login -u $DOCKER_USER --password-stdin docker.io
    - skopeo copy docker://registry.ci.spikedhand.com/handspiker2/ci-tools:$IMAGE_TAG docker://handspiker2/ci-tools:base
    # Update the `latest` tag to match `base`
    - skopeo copy docker://registry.ci.spikedhand.com/handspiker2/ci-tools:$IMAGE_TAG docker://handspiker2/ci-tools:latest
  when:
    branch:
    - ${CI_REPO_DEFAULT_BRANCH}
    event: *step_events