variables:
  - &build_image woodpeckerci/plugin-docker-buildx:5.0
  - &built_image_tag base-${CI_COMMIT_SHA}-${CI_PIPELINE_NUMBER}
  - &step_events [push, manual]


steps:
- name: Build Base Image
  image: *build_image
  settings:
    repo: registry.ci.spikedhand.com/handspiker2/ci-tools
    dockerfile: base.Dockerfile
    tags: 
      - *built_image_tag
    dry_run: false
    platforms: [linux/amd64]
  when:
    event: *step_events

# - name: Build&Publish Base Image
#   image: *build_image
#   settings:
#     <<: *build_settings
#     username:
#       from_secret: docker_username
#     password:
#       from_secret: docker_password
#     dry_run: false
#   when:
#     branch:
#     - ${CI_REPO_DEFAULT_BRANCH}
#     event: *step_events