matrix:
  PHP_VERSION:
    - 8.4.4
    - 8.3.17
    - 8.2.27
    - 8.1.31

variables:
  - &build_image woodpeckerci/plugin-docker-buildx:5.0
  - &step_events [push, manual]
  - &build_platforms [linux/amd64, linux/arm/v8]

depends_on: 
  - base

steps:
- name: Generate build arguments
  image: handspiker2/ci-tools:base
  commands: 
    - PHP_VERSION=${PHP_VERSION}
    - echo "php$${PHP_VERSION%.*}-${CI_COMMIT_SHA:0:8}-${CI_PIPELINE_NUMBER}" > .tags
    - echo "php$${PHP_VERSION%.*}" > .prod_tags
  when:
    event: *step_events
    
- name: Build Image
  image: *build_image
  settings:
    repo: registry.ci.spikedhand.com/handspiker2/ci-tools
    dockerfile: php.Dockerfile
    build_args:
      - "PHP_VERSION=${PHP_VERSION}"
      - "BASE_IMAGE=registry.ci.spikedhand.com/handspiker2/ci-tools:base-${CI_COMMIT_SHA:0:8}-${CI_PIPELINE_NUMBER}"
    auto_tag: false
    tags_file: .tags
    dry_run: false
    platforms: *build_platforms
  when:
    event: *step_events

- name: Publish Image
  image: handspiker2/ci-tools:docker
  environment:
    DOCKER_USER:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
    - echo $$DOCKER_PASSWORD | skopeo login -u $DOCKER_USER --password-stdin docker.io
    - export IMAGE_TAG="$$(cat .tags)"
    - export PUBLISH_TAG="$$(cat .prod_tags)"
    - skopeo copy docker://registry.ci.spikedhand.com/handspiker2/ci-tools:$$IMAGE_TAG docker://handspiker2/ci-tools:$$PUBLISH_TAG
  when:
    branch:
    - ${CI_REPO_DEFAULT_BRANCH}
    event: *step_events